userDatabaseDir: "userDatabase.json"
chatLogDir: "chatLog/"

adminUsers:
  - "boogieman002"

deviceConfigDir:
  - "../config/devices/manipulator.yaml"
  - "../config/devices/microscope.yaml"

streamConfigDir:
  - "../config/streams/twitch.yaml"
