# Device 1
name: 'Manipulator'
portName: ttyUSB0
portBaudRate: 9600
initialState: "Start"
confirmation: "OK"

cameras:
  - name: "Effector_View"
    portName: "/dev/video0"
  - name: "Wide_Shot"
    portName: "/dev/video2"
  - name: "Microscope_View"
    portName: "/dev/video4"

commands:
  - name: "Home"
    description: "Home the manipulator in all axes."
    requiredStates: ["Start", "home"]
    resultingState: "home"
    prefix: "home"
    output: "G28"
  - name: "Move Relative"
    description: "Move device by distance of millimeters."
    prefix: "moveBy"
    output: "G0 $XAxisDistance $YAxisDistance $ZAxisDistance"
    params:
      - name: "XAxisDistance"
        type: Integer
        range: [-100, 100]
      - name: "YAxisDistance"
        type: Integer
        range: [-100, 100]
        optional: true
        predefined: 0
      - name: "ZAxisDistance"
        type: Integer
        range: [-100, 100]
        optional: true
        predefined: 0
  - name: "Move Left"
    description: "Move device to the left by distance of millimeters."
    prefix: "l"
    output: "G0 -$XAxisDistance 0 0"
    params:
      - name: "XAxisDistance"
        type: Integer
        range: [0, 100]

  - name: "Move Right"
    description: "Move device to the right by distance of millimeters."
    prefix: "r"
    output: "G0 $XAxisDistance 0 0"
    params:
      - name: "XAxisDistance"
        type: Integer
        range: [0, 100]

  - name: "Move Up"
    description: "Move device up by distance of millimeters."
    prefix: "u"
    output: "G0 0 $YAxisDistance 0"
    params:
      - name: "YAxisDistance"
        type: Integer
        range: [0, 100]

  - name: "Move Down"
    description: "Move device down by distance of millimeters."
    prefix: "d"
    output: "G0 0 -$YAxisDistance 0"
    params:
      - name: "YAxisDistance"
        type: Integer
        range: [0, 100]

  - name: "Test Scenario"
    description: "Demo showcasing scenarios"
    requiredStates: [ "home" ]
    resultingState: [ "home" ]
    prefix: "test"
    vars: {
      X1: "50",
      X2: "0"
    }
    events: [
      "G91",
      "G0 $X1 0 0",
      "G0 $X2 0 0",
      "G90"
    ]
  - name: "Sponges Scenario"
    description: "Demo showcasing gripper capability by moving sponges around"
    requiredStates: [ "home" ]
    resultingState: [ "home" ]
    prefix: "sponges"
    vars: {
      X1: "-140",
      X2: "0",
      X3: "50",
      Y1: "80",
      Y2: "30",
      Y3: "-40",
      Y4: "-110",
      Z1: "-20",
      Z2: "0",
      Z3: "20",
      Z4: "30",
      GRIPPER1: "70",
      GRIPPER2: "100"
    }
    events: [
      "G91",
      "LIMITX 200",
      "LIMITY 200",
      "LIMITZ 100",
      "G0 $X1 $Y1 0",
      "G0 $X1 $Y2 $Z1",
      "M $GRIPPER1", # Grab the first sponge
      "G0 $X1 $Y2 $Z2",
      "G0 $X2 $Y3 $Z3",
      "G0 $X2 $Y4 $Z4",
      "G0 $X2 $Y4 $Z3",
      "M $GRIPPER2", # Deposit the first sponge
      "G0 $X2 $Y3 $Z2",
      "G0 $X1 $Y3 $Z1",
      "G0 $X1 $Y4 $Z1",
      "M $GRIPPER1", # Grab the second sponge
      "G0 $X1 $Y2 $Z3"
    ]
  - name: "Grab the microscope"
    description: "Grab the microscope"
    requiredStates: [ "home", "grab_sample_1" ]
    resultingState: "microscope_grabbed"
    prefix: "grab_micro"
    events: [
              "G90",
              "G0 posX -100 0",
              "M2 100",
              "G0 240 -145 0",
              "M2 30",
              "G0 240 -145 10",
              "G0 240 -50 10",
              "G0 0 -50 0",
              "G91"
    ]
  - name: "Put away the microscope"
    description: "Put away the microscope"
    requiredStates: [ "microscope_grabbed" ]
    resultingState: "home"
    prefix: "deposit_micro"
    events: [
      "G90",
      "G0 240 -50 10",
      "G0 240 -145 10",
      "G0 240 -145 0",
      "M2 100",
      "G0 240 -100 0",
      "G0 0 0 0",
      "G91"
    ]
  - name: "Grab sample 1"
    description: "Place sample 1 into the work area"
    requiredStates: [ "home" ]
    resultingState: "grab_sample_1"
    prefix: "grab_sample_1"
    #83 -200 -15
    #0 0 -35
    events: [
      "G90",
      "G0 83 -100 0",
      "G0 83 -200 0",
      "M2 100",
      "G0 83 -200 -15",
      "M2 30",
      "G0 83 -200 0",
      "G0 0 0 0",
      "G0 0 0 -35",
      "M2 100",
      "G0 0 0 0",
      "G91"
    ]
  - name: "Put away sample 1"
    description: "Put away sample 1"
    requiredStates: [ "grab_sample_1", "grabbed_micro", "home" ]
    resultingState: "home"
    prefix: "deposit_sample_1"
    events: [
      "G90",
      "G0 0 0 0",
      "M2 100",
      "G0 0 0 -35",
      "M2 30",
      "G0 0 0 0",
      "G0 83 -100 0",
      "G0 83 -200 0",
      "G0 83 -200 -15",
      "M2 100",
      "G0 83 -200 0",
      "G0 83 -100 0",
      "G0 0 0 0",
      "G91"
    ]