# Microscope
name: Microscope
portName: ttyUSB1
portBaudRate: 9600
confirmation: "DONE"
cameras:
  - name: "Main View"
    portName: "/dev/video4"
commands:
  - name: "Bed Light Switch"
    description: "Switch bed light ON and OFF."
    prefix: "bedLight"
    params:
      - name: "State"
        type: String
        values: [ "on", "off" ]
    output: "lgt bed $State"
  - name: "Top Light Switch"
    description: "Switch top light ON and OFF."
    prefix: "topLight"
    params:
      - name: "State"
        type: String
        values: [ "on", "off" ]
    output: "lgt top $State"
  - name: "Select sample"
    description: "Move sample selector to one of 5 possible positions"
    prefix: "sample"
    params:
      - name: "sample_number"
        type: Integer
        range: [1, 5]
    output: "sample $sample_number"